/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author suporte
 */
public class TelaNaoAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaNaoAluno
     */
    public TelaNaoAluno() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnReciclar3 = new model.projectButton();
        jLabel2 = new javax.swing.JLabel();
        txtDescartar = new model.projectTextField();
        lblDescartar = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        testReciclagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(480, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RecicloLogo_User.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 490, 180));

        btnReciclar3.setBackground(new java.awt.Color(60, 60, 60));
        btnReciclar3.setBorder(null);
        btnReciclar3.setForeground(new java.awt.Color(206, 240, 157));
        btnReciclar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/icons8-sinal-de-reciclagem-50.png"))); // NOI18N
        btnReciclar3.setToolTipText("");
        btnReciclar3.setColor(new java.awt.Color(60, 60, 60));
        btnReciclar3.setColorClick(new java.awt.Color(206, 240, 157));
        btnReciclar3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnReciclar3.setRadius(40);
        btnReciclar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciclar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnReciclar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 90, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(160, 205, 96));
        jLabel2.setText("gr");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 30, 30));

        txtDescartar.setBackground(new java.awt.Color(60, 60, 60));
        txtDescartar.setForeground(new java.awt.Color(160, 205, 96));
        txtDescartar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescartar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescartarActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 170, 80));

        lblDescartar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescartar.setForeground(new java.awt.Color(160, 205, 96));
        lblDescartar.setText("Descartar");
        jPanel1.add(lblDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(60, 60, 60));
        jSeparator4.setForeground(new java.awt.Color(70, 70, 70));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 480, 10));

        testReciclagem.setBackground(new java.awt.Color(60, 60, 60));
        testReciclagem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        testReciclagem.setForeground(new java.awt.Color(150, 150, 150));
        testReciclagem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        testReciclagem.setToolTipText("");
        testReciclagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(testReciclagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 470, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(480, 812));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReciclar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciclar3ActionPerformed

        AlunoLoginView.infotela = "NaoAluno";
        testReciclagem.setText("");

        float valor = Integer.parseInt(txtDescartar.getText());

        if(valor > 0) {
            TelaLoadingReciclando loadingreciclando = new TelaLoadingReciclando();
            this.setVisible(false);
            loadingreciclando.setVisible(true);
            //TODO Criar um insert no banco dados, preenchendo a quantidade (gramas) com o txt get text

        } else {
            testReciclagem.setText("Não há produto para reciclar");
        }
    }//GEN-LAST:event_btnReciclar3ActionPerformed

    private void txtDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescartarActionPerformed

    }//GEN-LAST:event_txtDescartarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNaoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private model.projectButton btnReciclar;
    private model.projectButton btnReciclar1;
    private model.projectButton btnReciclar3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDescartar;
    private javax.swing.JLabel testReciclagem;
    private model.projectTextField txtDescartar;
    // End of variables declaration//GEN-END:variables
}
